# Generated by Django 5.0.6 on 2026-06-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingjob',
            name='last_error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scrapingjob',
            name='last_task_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='scrapingjob',
            name='run_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='idle', max_length=20),
        ),
    ]
